### PR TITLE
Segmented controller to change tabs from outside

### PR DESCRIPTION
**Pull request by issakl**
Add "CustomSegmentedController" to add the ability to change the current tab from the parent widget.
The example code has been modified for all int Sliding controls

### CODE REVIEW

**Comment by hadukin** [comment]
@issakl Hi, you can change initialValue from parent widget, could you tell in more detail what problem the controller solves?

**Comment by issakl** [comment]
@hadukin Hi, the main issue is that I have a PageView and linked it with the segment controller, the initial value is to init the value for the controller. But when I need to change the tab programmatically on the page modified on page view or on some action, I need this controller to control the current tab index.

**Comment by hadukin** [comment]
@issakl 
I like the controller option, but I would like to make sure that it is really needed.
I made a small example, if I understand correctly, you want to get such behavior as in this example?
Can you please check if this solved your problem?

```
import 'package:custom_sliding_segmented_control/custom_sliding_segmented_control.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final PageController ctrl = PageController(initialPage: 0);
  int initial = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Example'),
      ),
      body: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(
              height: 100,
              child: PageView(
                onPageChanged: (v) {
                  setState(() {
                    initial = v;
                  });
                },
                controller: ctrl,
                children: [
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.red,
                  ),
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.green,
                  ),
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.yellow,
                  ),
                ],
              ),
            ),
            CustomSlidingSegmentedControl<int>(
              initialValue: initial,
              children: const {
                0: Text(
                  'zero',
                  textAlign: TextAlign.center,
                ),
                1: Text(
                  'one',
                  textAlign: TextAlign.center,
                ),
                2: Text(
                  'two',
                  textAlign: TextAlign.center,
                ),
              },
              onValueChanged: (int value) {
                setState(() {
                  initial = value;
                });
                ctrl.animateToPage(
                  value,
                  duration: const Duration(
                    milliseconds: 200,
                  ),
                  curve: Curves.linear,
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by issakl** [comment]
@hadukin
Yes, I've tested this code and for sure, it works 😎.
The difference in the code that I've pushed, is that no need to setState, and no need for rebuilding any widget (Just update the already built widget). I believe it has a better performance and better implementation because the initialValue should do what it's named to do (Init the segment controller value).

**Comment by hadukin** [comment]
@issakl 
I need some time to test the controller, once I'm sure everything works correctly I'll accept a pull request and add it to the library.
Thank you for your help

**Comment by Hilbert2048** [comment]
This functionality is effective, yet the thumb position does not adjust in response to the swipe gesture of the TabBarView/PageView. It would be ideal if it could seamlessly integrate with the gesture controls of a TabBarView or PageView.

**Pull request merged**
